import fs from 'node:fs';
import path from 'node:path';
import { describe, expect, it } from 'vitest';

const html = fs.readFileSync(path.resolve('index.html'), 'utf8');
const css = fs.readFileSync(path.resolve('src/styles.css'), 'utf8');

describe('files upload UI', () => {
  it('exposes a PG files upload button and modal drag/drop form', () => {
    const filesSectionIndex = html.indexOf('class="files-section"');
    expect(filesSectionIndex).toBeGreaterThan(-1);

    const uploadButtonIndex = html.indexOf('class="files-upload-open-btn"', filesSectionIndex);
    const uploadModalIndex = html.indexOf('class="doc-modal-backdrop files-upload-modal-backdrop"', filesSectionIndex);
    const filesListIndex = html.indexOf('class="files-list"', filesSectionIndex);

    expect(uploadButtonIndex).toBeGreaterThan(filesSectionIndex);
    expect(uploadModalIndex).toBeGreaterThan(uploadButtonIndex);
    expect(uploadModalIndex).toBeLessThan(filesListIndex);
    expect(html).toContain('@drop.prevent="$store.chat.handleFilesPageDrop($event)"');
    expect(html).toContain('@change="$store.chat.handleFileUploadInput($event)"');
    expect(html).toContain('@click="$store.chat.closeFileUploadPanel()"');
    expect(html).not.toContain('@click.self="$store.chat.closeFileUploadPanel()"');
    expect(html).not.toContain('class="modal-close" type="button" @click="$store.chat.closeFileUploadPanel()"');
    expect(html).toContain('files-upload-modal-close-btn');
    expect(html).toContain('x-show="$store.chat.fileUploadOpen && !$store.chat.showWriteContextModal && $store.chat.isTowerPgMode"');
    expect(html).toContain(':aria-hidden="(!$store.chat.fileUploadOpen || $store.chat.showWriteContextModal).toString()"');
    expect(html).toContain('files-upload-modal-footer');
    expect(html).toContain('>Close</button>');
    expect(html).toContain('class="files-upload-status-btn"');
    expect(html).toContain('x-show="$store.chat.hasActiveFileUploads"');
    expect(html).toContain('x-text="$store.chat.fileUploadToolbarLabel"');
    expect(html).toContain('Uploads keep running if this modal is closed.');
    expect(html).toContain('files-upload-toast');
    expect(html).toContain('$store.chat.clearFileUploadNotice()');
    expect(html).toContain('@click="$store.chat.createFileFolderFromPrompt()"');
    expect(html).toContain('Select multiple');
    expect(html).toContain('$store.chat.toggleFileSelectionMode()');
    expect(html).toContain('files-selection-bar');
    expect(html).toContain('currentFileFolderBreadcrumbs');
    expect(html).toContain('currentFileChildFolders');
    expect(html).toContain('@dragstart="$store.chat.handleFileRowDragStart(row, $event)"');
    expect(html).toContain('@drop="$store.chat.handleFileFolderDrop(folder, $event)"');
    expect(html).toContain('x-show="$store.chat.fileSelectionMode && $store.chat.canMoveFileBrowserRow(row)"');
    expect(html).toContain('x-model="item.name"');
    expect(html).toContain('x-model="item.scope_id"');
    expect(html).toContain('x-model="item.folder_id"');
    expect(html).toContain('x-show="$store.chat.canEditFileBrowserRow(row)"');
    expect(html).toContain('@click="$store.chat.openFileEditModal(row)"');
    expect(html).toContain('id="file-edit-title"');
    expect(html).toContain('x-model="$store.chat.fileEditName"');
    expect(html).toContain('x-model="$store.chat.fileEditScopeId"');
    expect(html).toContain('x-model="$store.chat.fileEditChannelId"');
    expect(html).toContain('x-model="$store.chat.fileEditFolderId"');
    expect(html).toContain('Changing scope or channel can make this file inaccessible in previous chat threads');
    expect(html).toContain('fileEditProgressText');
    expect(html).toContain('role="status"');
    expect(html).toContain("fileEditAction === 'convert'");
    expect(html).toContain("fileEditAction === 'save'");
    expect(css).toContain('.files-upload-modal-backdrop');
    expect(css).toContain('.files-upload-modal');
    expect(css).toContain('max-height: min(88dvh, 820px)');
    expect(css).toContain('.files-upload-queue');
    expect(css).toContain('overflow-y: auto');
    expect(css).toContain('.files-upload-toast');
    expect(css).toContain('.files-upload-status-btn');
    expect(css).toContain('.files-upload-status-track');
    expect(css).toContain('.files-upload-modal-actions');
    expect(css).toContain('.files-upload-modal-close-btn');
    expect(css).toContain('.files-upload-modal-footer');
  });

  it('renders shared folders inside Files and removes standalone Drive navigation', () => {
    const filesSectionIndex = html.indexOf('class="files-section"');
    const towerFilesIndex = html.indexOf('class="files-list"', filesSectionIndex);
    const sharedSectionIndex = html.indexOf('class="files-shared-section"', filesSectionIndex);
    const editModalIndex = html.indexOf('class="doc-modal-backdrop file-edit-modal-backdrop"', filesSectionIndex);

    expect(sharedSectionIndex).toBeGreaterThan(towerFilesIndex);
    expect(sharedSectionIndex).toBeLessThan(editModalIndex);
    expect(html).not.toContain("$store.chat.navigateTo('drive')");
    expect(html).not.toContain("$store.chat.navSection === 'drive'");
    expect(html).not.toContain('class="drive-panel"');
    expect(html).toContain('$store.chat.startDrive()');
    expect(html).toContain('@destroy="$store.chat.stopDrive()"');
    expect(html).toContain('id="files-shared-title"');
    expect(html).toContain('aria-label="Shared folder sources"');
    expect(html).toContain('@click="$store.chat.refreshDrive()"');
    expect(html).not.toContain('@click="$store.chat.openDriveEntry(entry, true)"');
    expect(html).toContain('aria-label="FipsDrive folder breadcrumb"');
    expect(html).toContain('<strong>FipsDrive</strong>');
    expect(html).toContain('@click="$store.chat.activateDriveEntry(entry)"');
    expect(html).toContain('@click="$store.chat.cancelDriveTransfer()"');
    expect(html).toContain('@click="$store.chat.copyDriveDiagnostics()"');
    expect(html).toContain('@click="$store.chat.clearDriveDiagnostics()"');
    expect(html).toContain('Shared folder unavailable. Copy diagnostics');
    expect(html).toContain('x-text="$store.chat.driveStatusLabel"');
    expect(html).toContain("files-workspace-shared-collapsed");
    expect(html).toContain("filesMobilePane: 'tower'");
    expect(html).toContain('class="files-mobile-switcher"');
    expect(html).toContain('aria-label="Files source"');
    expect(html).toContain('>FIPS Drive</span>');
    expect(html).toContain("@click=\"filesMobilePane = 'shared'; $store.chat.filesSharedPanelCollapsed = false\"");
    expect(html).toContain("'files-mobile-shared-active': filesMobilePane === 'shared'");
    expect(html).toContain("x-show=\"!$store.chat.filesSharedPanelCollapsed\"");
    expect(html).toContain('aria-label="Collapse shared folders panel"');
    expect(html).toContain('aria-label="Show FipsDrive panel"');
    expect(css).toContain('.files-shared-browser');
    expect(css).toContain('.files-workspace');
    expect(css).toContain('grid-template-columns: minmax(0, 2fr) minmax(320px, 1fr)');
    expect(css).toContain('.files-workspace-shared-collapsed');
    expect(css).toContain('.files-mobile-switcher');
    expect(css).toContain('.files-mobile-shared-active .files-main-pane');
    expect(css).toContain('.files-workspace:not(.files-mobile-shared-active) .files-shared-section');
    expect(css).toContain('calc(5rem + env(safe-area-inset-bottom, 0px))');
    expect(css).toContain('.files-shared-list');
    expect(css).toContain('.files-drive-diagnostics');
    expect(css).toContain('@media (max-width: 700px)');
  });
});
