import { beforeEach, describe, expect, it, vi } from 'vitest';
vi.mock('../src/wapp-image-upload.js', async original => ({ ...await original(), uploadWappImage: vi.fn() }));
import { uploadWappImage } from '../src/wapp-image-upload.js';
import { wappImageManagerMixin } from '../src/wapp-image-manager.js';
const store = () => Object.assign(Object.create(wappImageManagerMixin), { personalWappEditorOpen: true, personalWappFormIconUrl: 'https://old/icon.png', currentWorkspace: { workspaceId: 'one' } });
const select = s => s.selectPersonalWappImage({ target: { files: [new File(['png'], 'icon.png', { type: 'image/png' })], value: 'file' } });
beforeEach(() => { vi.restoreAllMocks(); uploadWappImage.mockReset(); vi.spyOn(URL, 'createObjectURL').mockReturnValue('blob:preview'); vi.spyOn(URL, 'revokeObjectURL').mockImplementation(() => {}); });
describe('WApp image editor lifecycle', () => {
  it('previews without uploading; successful upload sets the persisted icon field', async () => { const s = store(); select(s); expect(s.personalWappImagePreview).toBe('blob:preview'); expect(uploadWappImage).not.toHaveBeenCalled(); uploadWappImage.mockResolvedValue('https://primal/icon.png'); await s.uploadPersonalWappImage(); expect(s.personalWappFormIconUrl).toBe('https://primal/icon.png'); expect(s.personalWappImagePending).toBe(false); });
  it('preserves old URL on failure and allows retry', async () => { const s = store(); select(s); uploadWappImage.mockRejectedValueOnce(new Error('offline')).mockResolvedValueOnce('https://primal/retry.png'); await s.uploadPersonalWappImage(); expect(s.personalWappFormIconUrl).toBe('https://old/icon.png'); expect(s.personalWappImageError).toBe('offline'); expect(s.personalWappImagePending).toBe(true); await s.uploadPersonalWappImage(); expect(s.personalWappFormIconUrl).toContain('retry'); });
  it.each(['replace', 'close', 'workspace', 'manual'])('ignores stale completion after %s', async action => { const s = store(); select(s); let finish; uploadWappImage.mockImplementation(() => new Promise(resolve => { finish = resolve; })); const pending = s.uploadPersonalWappImage(); if (action === 'replace') select(s); if (action === 'close') { s.resetPersonalWappImage(); s.personalWappEditorOpen = false; } if (action === 'workspace') s.currentWorkspace = { workspaceId: 'two' }; if (action === 'manual') { s.resetPersonalWappImage(); s.personalWappFormIconUrl = 'https://manual/icon.png'; } finish('https://stale/icon.png'); await pending; expect(s.personalWappFormIconUrl).not.toContain('stale'); expect(s.personalWappImageBusy).toBe(false); });
  it('ignores file picker cancellation and prevents duplicate upload', async () => { const s = store(); select(s); s.selectPersonalWappImage({ target: { files: [] } }); expect(s.personalWappImagePreview).toBe('blob:preview'); let finish; uploadWappImage.mockImplementation(() => new Promise(resolve => { finish = resolve; })); const pending = s.uploadPersonalWappImage(); await s.uploadPersonalWappImage(); expect(uploadWappImage).toHaveBeenCalledTimes(1); s.resetPersonalWappImage(); expect(uploadWappImage.mock.calls[0][1].signal.aborted).toBe(true); expect(URL.revokeObjectURL).toHaveBeenCalledWith('blob:preview'); finish('https://stale/icon.png'); await pending; });
});
